apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    'backstage.io/techdocs-ref': dir:.  
    'backstage.io/kubernetes-id': dice-roller
    'backstage.io/kubernetes-namespace': dice-space
spec:
  type: service
  owner: ${{ values.owner | dump }} 
  lifecycle: experimental
